### ISSUE TITLE
Not running on Fedora

### ISSUE THREAD

**Issue by neo1999a** [goldendict/goldendict#1227] opened 2020-01-28 15:57 UTC
Hi, I installed goldendict on "Fedora 31" but its not working and say this :

$goldendict 
QSocketNotifier: Can only be used with threads started with QThread
No favorities file found
Load done
getResource: gdlookup://localhost?blank=1
scheme: gdlookup
host: localhost
getResource: gdlookup://localhost?word=Welcome!&group=4294967295
scheme: gdlookup
host: localhost
In-place finish.
getResource: gdlookup://localhost?blank=1
scheme: gdlookup
host: localhost
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
Segmentation fault (core dumped)
------------------------------------------------------------------

**Comment by vedgy** [comment] 2020-01-29 06:16
For crashes in distribution-provided packages check the distro bug tracker and possibly file a bug there first: https://bugzilla.redhat.com/buglist.cgi?component=goldendict&product=Fedora. A workaround is suggested under https://bugzilla.redhat.com/show_bug.cgi?id=1766935 in case you are using Wayland.

If this bug turns out to be a duplicate Wayland crash bug or if it is caused by a distro packaging error, please close it. Otherwise attach a backtrace, e.g. using `coredumpctl`.

**Comment by xvitaly** [comment] 2020-03-15 10:24
Can you try with fix: https://bodhi.fedoraproject.org/updates/FEDORA-2020-64569ed421

Added a desktop action GoldenDict (X11) for users with crashes on Wayland. You can select it from launcher menu.

**Closed** 2020-03-15 10:39 UTC
