### ISSUE TITLE
Too many & symbols in names of dictionary groups

### ISSUE THREAD

**Issue by embar-** [goldendict/goldendict#847] opened 2017-06-01 19:20 UTC
Somewhere between 1.5.0rc2.git.20161226T19173 and 1.5.0rc2+git.20170314T174738 GoldenDict started to add too many & symbols in dictionary groups. See attachment.

[test.zip](https://github.com/goldendict/goldendict/files/1045792/test.zip)

**Comment by Abs62** [comment] 2017-06-01 20:32
Can't reproduce. Where did the first "&" come from? I don't see it in the input field on your video.

**Comment by embar-** [comment] 2017-06-01 20:44
I never entered & symbol. I just enter "Some name" as group name. After confirming name, I see m letter with underline in tab. I only close dialog and in list of groups I started to see "So&me name".

**Comment by Abs62** [comment] 2017-06-01 21:07
Hm. GD never add ampersands to group names voluntarily.

**Comment by embar-** [comment] 2017-06-02 03:07
I guess It adds ampersand for keyboard shortcut while displaying names in titles. But unintentionally somehow it remains permanent for name.

**Comment by Abs62** [comment] 2017-06-02 07:20
GD don't add any shortcuts to tabs in groups dialog. GD even don't allow to add it manually, ampersands are considered as part of group name but not shortcut prefix.

**Comment by embar-** [comment] 2017-06-02 08:34
Now I tested builds for Windows, these are not affected:
GoldenDict-1.5.0-RC2-85-g473cb2b_(QT_562) 2017-03-31 
GoldenDict-1.5.0-RC2-85-g473cb2b_(QT_486) 2017-03-31

Regarding openSUSE Linux builds, I can reproduce in 
goldendict-1.5.0~rc2+git.20170316T210955 with Qt 5.6.1
goldendict-1.5.0~rc2+git.20170601T224956 with Qt 5.8.0
But I can NOT reproduce in
goldendict-1.5.0rc2.git.20161226T19173 with Qt 4.8.6
goldendict-1.5.dev-20170204.1 with Qt 4.8.6

Maybe this bug related with Qt5 in Linux only?..

**Comment by Abs62** [comment] 2017-06-02 10:18
I have tried now last git version under Ubuntu with Qt 5.4.2 - not reproduced.

**Comment by embar-** [comment] 2017-06-04 12:42
For testing, please try https://susestudio.com/a/CttYWz/lietukas-42-1-multilingual (after login, you can download https://susestudio.com/a/CttYWz/lietukas-42-1-multilingual/download/iso to get ISO for using in real machine or in VirtualBox; your can also test via TestDrive in browser (i.e. without downloading), but in this later case will not have access to internet)- here I can consistently reproduce by these steps:
1. Start GolDendict
2. Press F3
3. Go to tab "Groups". You can see predefined groups. If you press "Rename group" button and simply press OK, it will add & for current group name. If you press OK for whole dialog, it will add & for every/each group name.

**Comment by timofonic** [comment] 2017-07-07 20:37
Any news about this? I'm interested in knowing what's going to happen.

**Comment by pwliao** [comment] 2017-07-26 12:07
Are you using KDE?
See
[https://stackoverflow.com/questions/32688153/how-to-disable-automatic-mnemonics-in-a-qt-application-on-kde](https://stackoverflow.com/questions/32688153/how-to-disable-automatic-mnemonics-in-a-qt-application-on-kde)
[https://bugs.kde.org/show_bug.cgi?id=337491](https://bugs.kde.org/show_bug.cgi?id=337491)

Try to add
```
[Development]
AutoCheckAccelerators=false
```
to `~/.config/kdeglobals`

**Comment by embar-** [comment] 2017-07-30 10:57
Yes, I use KDE Plasma 5.8 desktop and editing ~/.config/kdeglobals helped!

**Comment by Knusper** [comment] 2019-10-27 01:19
As you can see, this bug has recently been fixed upstream in KDE. Users of older versions of KDE (such as e.g. in debian buster) need to apply the fix.

**Comment by xiaoyifang** [comment] 2023-04-30 01:52
can be closed as solved

**Closed** 2023-04-30 05:34 UTC
