### ISSUE TITLE
Update the early access builds?

### ISSUE THREAD

**Issue by ingjieye** [goldendict/goldendict#1348] opened 2021-02-04 02:26 UTC
It's almost two years since the latest early access builds released. Consider updating the early access builds?
https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows

**Comment by nikita-moor** [comment] 2021-02-10 11:27
Duplicate #953

**Comment by masterrite** [comment] 2021-02-17 18:53
I concur.
 
By the way, it doesn't matter if this is a duplicate of an issue opened in 2018 if it's 2021 and we still don't have an update for the early access builds. The fact that the latest EA build for windows is from 2019 and someone can still accuse this new issue to be a duplicate from 3 years ago is ironic.

**Comment by nikita-moor** [comment] 2021-02-17 19:13
@masterrite, if your intention is to find the most recent version, then see my answer above. The latest binary corresponds with the most recent commit of 2021-02-13.

P.S. There is a problem, ticket #953 is open, that's all we can do, no need to molest developers.

**Comment by masterrite** [comment] 2021-02-17 19:29
> @masterrite, if your intention is to find the most recent version, then see my answer above. The latest binary corresponds with the most recent commit of 2021-02-13.
> 
> P.S. Problem exists, ticket #953 is open, that's all we can do, no need to molest developers.

#953 points me to a Russian forum for the latest build, as well as a comment from Gentoo bot saying it's "masked for removal". It isn't solving the problem except informing us that there are incremental updates, and yes, I found your comment there in November 2020 inviting people to build and update the windows EA in the wiki, but apparently no one is doing it.

I'm not molesting developers. I'm pointing out a problem. An average user cannot verify the binary against a commit, or use the binary for anything. Is the build on the Windows EA wiki up to date? The text on the wiki page still says "1.5.0-RC2-372-gc3ff15f, Date: 27 April 2019".

Frankly the devs can do better by simply building and updating the wiki page for Windows and Mac EAs instead of just keeping #953 open. It's hardly molesting anyone to ask for that.

**Comment by nonwill** [comment] 2021-02-17 21:43
@masterrite  Anyway, private builds of most recent version with **_OCR_** support are available at [my site](https://nonwill.github.io/post/goldendict/)

**Comment by masterrite** [comment] 2021-02-19 18:37
> @masterrite Anyway, private builds of most recent version with **_OCR_** support are available at [my site](https://nonwill.github.io/post/goldendict/)

Thanks! I've been looking for your build since I remembered how you fixed a conflict with snipaste.

**Comment by loyukfai** [comment] 2022-05-25 15:43
Tried these?

https://github.com/xiaoyifang/goldendict/releases

**Comment by nonwill** [comment] 2022-06-18 02:28
Hi, @loyukfai 
[New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).

**Comment by loyukfai** [comment] 2022-06-18 16:36
@nonwill Thanks for notifying but I'm partial towards @xiaoyifang builds because he seems to respect the GPL and other people.

Cheers.

**Comment by nonwill** [comment] 2022-06-18 17:11
> I'm partial towards @xiaoyifang builds because he seems to respect the GPL and other people.
> 
> Cheers.

@loyukfai : I adore you so much for that [you are much more faithful than the guy who changes his username from time to time](https://github.com/goldendict/goldendict/issues/1424#issue-1049877413).

**Comment by vedgy** [comment] 2022-09-26 09:01
Some @yakupcengo recently replaced a link on this page with a tracking link too: https://github.com/goldendict/goldendict/wiki/GoldenDict-as-a-Desktop-Google-Translate-App/_history.

@Abs62, can you block wiki updates for non-members?

A less reliable approach is to report the vandals to GitHub and get their accounts blocked. But they can always register another account...

**Comment by nonwill** [comment] 2022-10-17 21:15
Windows.Media.Ocr supported by [GoldenDict++OCR](https://nonwill.github.io/gdocr/GoldenDict-OCR-Language-Settings/) as OCR **[plugin](https://nonwill.github.io/gdocr/cn/GoldenDict-OCR-Plugins-Interface/)** now：
Name | File Name | Platform | Ratings | Remarks
-- | -- | -- | -- | --
MacVision | gdp.ocr.macvision.* | macOS 10.15/11/12 | ***** | **_Apple’s Vision framework_** |
**_WinRT Ocr_** | gdp.ocr.**_winrtocr_**.* | Windows 8/10/11 | ***** | **_Windows.Media.Ocr_** |
Tesseract | gdp.ocr.tesseract.* | All | ***** | **_Tesseract_** |
Nicomsoft | gdp.ocr.nicomsoft.* | Windows | *** | **_Nicomsoft OCR_** |
winmask | gdp.gsc.winmask.* | Windows/Linux | ***** | Taking **_dynamic shot_**. |
fromcliboard | gdp.gsc.fromcliboard.* | All | ***** | **_External tools_**. |

![](https://nonwill.github.io/media/goldendict/winrt_ocr.png)
![](https://nonwill.github.io/media/goldendict/winrt_ocr_add.gif)
[ #1254](https://github.com/goldendict/goldendict/issues/1254)

**Comment by nonwill** [comment] 2022-10-20 00:24
[**Windows.Media.Ocr** / **QCamera Capture**](https://nonwill.github.io/gdocr/GoldenDict-OCR-Language-Settings) supported by [**GoldenDict++OCR**](https://nonwill.github.io/gdocr/) as **_OCR_** / **Image Capture** **[plugin](https://nonwill.github.io/gdocr/cn/GoldenDict-OCR-Plugins-Interface/)** now：
Name | File Name | Platform | Ratings | Remarks
-- | -- | -- | -- | --
MacVision | gdp.ocr.macvision.* | macOS 10.15/11/12 | ***** | **_Apple’s Vision framework_** |
**_WinRT Ocr_** | gdp.ocr.**_winrtocr_**.* | **_Windows 8/10/11_** | ***** | **_Windows.Media.Ocr_** |
Tesseract | gdp.ocr.tesseract.* | All | ***** | **_Tesseract_** |
Nicomsoft | gdp.ocr.nicomsoft.* | Windows | *** | **_Nicomsoft OCR_** |
winmask | gdp.gsc.winmask.* | Windows/Linux | ***** | Taking **_dynamic shot_**. |
fromcliboard | gdp.gsc.fromcliboard.* | All | ***** | **_External tools_**. |
**_qtcamera_** | gdp.gsc.**_qtcamera_**.* | **_All_** | **** | **_Image capture using QCamera_**. |

![](https://nonwill.github.io/media/goldendict/winrt_ocr.png)
![](https://nonwill.github.io/media/goldendict/winrt_ocr_add.gif)
[ #1254](https://github.com/goldendict/goldendict/issues/1254)

**Comment by mnixry** [comment] 2022-11-21 16:23
> [**Windows.Media.Ocr** / **QCamera Capture**](https://nonwill.github.io/gdocr/GoldenDict-OCR-Language-Settings) supported by [**GoldenDict++OCR**](https://nonwill.github.io/gdocr/) as **_OCR_** / **Image Capture** **[plugin](https://nonwill.github.io/gdocr/cn/GoldenDict-OCR-Plugins-Interface/)** now

@nonwill Please respect the open source license of GoldenDict. In accordance with Section 6 of the [GPLv3 license](https://github.com/goldendict/goldendict/blob/master/LICENSE.txt), you are required to distribute the source code of your fork under the same license as you distribute the binary distribution. Violating the rules of open source community will harm the common rights of users.

**Comment by nonwill** [comment] 2022-11-22 11:25
@mnixry 
>Violating the rules of open source community will harm the common rights of users.

Thanks for the heads up and so let's go to #1424 to discuss this issue.

**Comment by vedgy** [comment] 2023-05-11 12:51
> Some guys are constantly vandalizing the wiki, please stop them?

Seems the spammer attack on the GoldenDict Wiki has stopped. So this is currently not a problem. Please log a separate issue when/if the vandalism recurs.

Closing as a duplicate of https://github.com/goldendict/goldendict/issues/953.

**Closed by vedgy** 2023-05-11 12:51 UTC
