### ISSUE TITLE
[FEATURE REQUEST] "Disable touchpad zoom" in options

### ISSUE THREAD

**Issue by IvanD155** [goldendict/goldendict#805] opened 2017-01-24 01:04 UTC
Dear Developers,

I want to thank you for maintaining such a wonderful project as GoldenDict!

The only one issue is bothering me for a long time. I use GoldenDict on OS X and it is extremely annoying that I accidentally zooming in or out the articles while trying to scroll up or down.

With other applications on OS X it is not the case. Scrolling with two fingers and zooming with two finger are messed up extremely rare. However, in GoldenDict it happens all the time.

Could you possibly add "Disable touchpad zoom" to Preferences in GoldenDict?

Best regards,
Ivan

**Comment by imkaihao** [comment] 2018-09-18 03:33
I have faced the same problem.

**Comment by HaitaoShi** [comment] 2019-05-21 13:17
me too

**Comment by Chandler-Lu** [comment] 2019-12-17 01:04
me too~

**Comment by zhangweijie666** [comment] 2020-01-05 02:56
me foo, any methods to solve?

**Comment by HaitaoShi** [comment] 2020-01-05 10:36
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    Hi, not really, but you can use ‘command' and ‘+' instead.  
    
      
    
        
                    
 
    

    On 01/5/2020 02:56，zhangweijie666<notifications@github.com> wrote： 


me foo, any methods to solve?

**Comment by sofire** [comment] 2020-02-08 02:00
me too.

**Comment by giorgiopagnoni** [comment] 2020-02-26 16:19
... me too

**Comment by oracleyue** [comment] 2021-02-08 09:53
Wish this could be disabled at least for OS X users! 
I guess, due to QT bug, scrolling frequently trigger zooming. This is really annoying. Thanks!

**Comment by giorgiopagnoni** [comment] 2021-02-08 10:06
> Wish this could be disabled at least for OS X users!
> I guess, due to QT bug, scrolling frequently trigger zooming. This is really annoying. Thanks!

Yes it's really annoying, it either zooms in or out, or goes back/forward in history. Related: https://github.com/goldendict/goldendict/issues/1241

**Comment by Andrewlearntocode** [comment] 2023-07-31 04:59
I tried to use an app called BetterTouchTool to redefine the zoom in/out gesture in GoldenDict. Guess what happed? GoldenDit override the rules set in BetterTouchTool. Such thing never happens in other apps.

I even tried by disabling the pinch gesture of touchpad in the system setting, same thing happened. GoldenDict override the system setting and keeping the function of pinch to zoom in/out.

What a bug!

**Comment by vedgy** [comment] 2023-07-31 15:06
Closing as a duplicate of #668

**Closed by vedgy** 2023-07-31 15:06 UTC
