### ISSUE TITLE
[proposal] to add settings for creating a new tab of word when using 'pop up'

### ISSUE THREAD

**Issue by Aliaksandr3by** [goldendict/goldendict#1671] opened 2023-09-28 11:05 UTC
I want to create a new tab in the main window of program when I click on the icon 'Send word to..', not overwrite old one.

![image](https://github.com/goldendict/goldendict/assets/11432724/4764d8d9-c10b-4a12-851a-ab588ff4ad8d)

**Comment by vedgy** [comment] 2023-09-28 11:17
Duplicate of #1353.

**Closed by vedgy** 2023-09-28 11:17 UTC
