### ISSUE TITLE
QtWebKitWidgets has been replaced by QtWebEngineWidgets

### ISSUE THREAD

**Issue by fdservices** [goldendict/goldendict#1655] opened 2023-06-12 08:12 UTC
QtWebKit is being replaced by QtWebEngine

[https://wiki.qt.io/QtWebEngine/Porting_from_QtWebKit](url)

So build now will fail with `Project ERROR: Unknown module(s) in QT: webkitwidgets` on newer systems.

**Comment by vedgy** [comment] 2023-06-12 08:20
Closing as a duplicate of #1081.

You can merge #1542 into goldendict master and pass `"CONFIG+=use_qtwebengine"` to `qmake`. Make sure to read the PR's description. Report issues or suggestions at [vedgy/goldendict](https://github.com/vedgy/goldendict).

**Closed by vedgy** 2023-06-12 08:20 UTC

**Comment by fdservices** [comment] 2023-06-12 08:33
Sorry, I searched for the error message.

May be mention `"CONFIG+=use_qtwebengine"` in the build instructions?

**Comment by vedgy** [comment] 2023-06-12 13:02
Sorry, I forgot to mention other options. You can build Qt WebKit modules from sources if you prefer the much more widely used and tested main GoldenDict version. Quote from the official GoldenDict README:
> Note: In Qt 5.6.0 and later the Webkit module was removed from official release builds. You should build it from sources to compile GoldenDict.

Also many GNU/Linux distributions still offer Qt 5 WebKit[Widgets] packages.
