### ISSUE TITLE
[mistake] if I get "e.g." program trims last dot, but "Exempli gratia (е. g.)". that goes to error

### ISSUE THREAD

**Issue by Aliaksandr3by** [goldendict/goldendict#1366] opened 2021-03-17 01:44 UTC
[mistake] if I get "e.g." program trims last dot, but "Exempli gratia (е. g.)". that goes to error

maybe will be best if it do not trim last point if word has many dots?

or using the system like the capture2text?

![image](https://user-images.githubusercontent.com/11432724/111401925-4ba50d80-86db-11eb-86ad-a64eb9878fac.png)

**Comment by vedgy** [comment] 2021-03-17 07:43
Duplicate of #1350?

**Closed** 2021-03-17 12:06 UTC
