### ISSUE TITLE
Rendering Persian/Arabic text in Linux

### ISSUE THREAD

**Issue by ilius** [goldendict/goldendict#1329] opened 2020-12-15 07:57 UTC
GoldenDict has real issues in rendering Persian/Arabic text, which makes it unusable for these languages (plus Urdo and any language based on [Arabic script](https://en.wikipedia.org/wiki/Arabic_script)).

Here are 2 examples of what Aard2 web app shows in Firefox, which is how it should look like:

![aard2-fa-test1](https://user-images.githubusercontent.com/197648/102185866-fb919180-3ec6-11eb-981a-d78eddb8f540.png)
![aard2-fa-test2](https://user-images.githubusercontent.com/197648/102185873-fe8c8200-3ec6-11eb-8a1e-2c47f7eec18c.png)

And here is what GoldenDict shows for these two entries:
![goldendict-fa-test](https://user-images.githubusercontent.com/197648/102185917-1237e880-3ec7-11eb-8d20-9dac0d554096.png)

I have also customized the font via a style, using [Shabnam font](https://github.com/rastikerdar/shabnam-font) which is %100 standard Persian font. Although I don't think this issue is related to font, as I have tried other standard fonts like Tahoma, FreeSans, etc and it doesn't effect this problem.

GoldenDict Version: `1.5.0-RC2+git`
Based on Qt 5.15.1 (GCC 9.3.0, 64 bit)
Operating System: Debian GNU/Linux, bullseye/sid

**Comment by ilius** [comment] 2020-12-15 08:02
Another part of the same "test" entry:
![goldendict-fa-test2](https://user-images.githubusercontent.com/197648/102187169-e584d080-3ec8-11eb-8096-7c679813723e.png)

Here is the html source for the short "Test" entry:

	<html><head></head><body><div><div dir="rtl">
	<font color="green">مخفف</font>
	<br>عهد (مثلا عهد عتیق)<br>
	</div></div></body></html>

And the long "test" entry:
[test.zip](https://github.com/goldendict/goldendict/files/5694195/test.zip)

**Comment by vedgy** [comment] 2020-12-15 10:38
The unofficially maintained Qt WebKit could be at fault. There are already requests to remove this dependency and port to Qt WebEngine: #677, #1081.

**Comment by ilius** [comment] 2020-12-15 11:18
@vedgy Thanks for the info.
I will try to compile with Qt4 to use until it's fixed.

**Comment by ilius** [comment] 2020-12-15 17:20
It works perfectly with Qt4.
For other users, here is how to build with Qt4 on Debian-based systems:
https://gist.github.com/ilius/0fef65b0512e1f8fa7c2d258be98c515

**Comment by vedgy** [comment] 2020-12-15 17:26
@ilius, if this issue is a duplicate of #1150, please close it. There is more information in comments to that earlier issue.

**Closed** 2020-12-15 17:27 UTC
