### ISSUE TITLE
New Stable Release?

### ISSUE THREAD

**Issue by gapplef** [goldendict/goldendict#910] opened 2017-10-18 09:10 UTC
I wander why no stable release for 7 years.
You guys may think the code is still not stable and not suitable for daily use. But 7 years is just too long for a new stable release.

Ubuntu package maintainer actually packaged those **unstable  and not suitable for daily use** code for their user. And many people are using the **unstable** package on Ubuntu.
https://launchpad.net/ubuntu/+source/goldendict

And Souls(A new promising rolling release Linux distributions) just wouldn't package this software for there is no new stable release for too long times.
https://dev.solus-project.com/T870

Why not just make smaller but more frequent stable release, like half or one year per release.

**Comment by vedgy** [comment] 2023-05-11 12:42
Closing as a duplicate of a more commented-on #953.

**Closed by vedgy** 2023-05-11 12:42 UTC
