### ISSUE TITLE
Persian/Arabic dictionaries not showing properly when compiling app using Qt5

### ISSUE THREAD

**Issue by footing11** [goldendict/goldendict#1550] opened 2022-09-10 09:10 UTC
![57134815-f3094780-6dc4-11e9-9cff-8f3bfbd66db8](https://user-images.githubusercontent.com/32715481/189476826-68b1645b-1a7d-41de-a021-c723ab06cc5f.png)

 compiling it from binary with qt4-qmake fixes this issue. 
But qt4 is old and is not supported after debian 10. We don't have it on Bullseye.
So please fix this issue on application when compiling using qt5.
Thanks,

**Comment by vedgy** [comment] 2022-09-10 11:42
Why create a duplicate of #1150 where your have commented before? This is an upstream Qt WebKit issue. It is unlikely to be fixed any time soon, because Qt WebKit is practically unmaintained.

#1542 is in the process of adding support for Qt WebEngine. Qt-WebEngine-based builds of GoldenDict should not have this issue. But the porting is not complete. Some features don't work yet.

**Comment by footing11** [comment] 2022-09-10 11:50
Oh ok.
Sorry I thought that issue is being fixed or closed due to people could be able to recompile it using Qt 4.

**Comment by vedgy** [comment] 2022-09-10 11:53
That issue is open. Please close this one as duplicate.

**Closed** 2022-09-10 11:54 UTC
