### ISSUE TITLE
Is a successful installtion?

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [goldendict/goldendict#1001] opened 2018-04-26 08:34 UTC
That is what i receive after make install
`jigao@jigao-CW35S:~/goldendict$ sudo make install
install -m 755 -p "goldendict" "/usr/local/bin/goldendict"
strip "/usr/local/bin/goldendict"
install -m 644 -p /home/jigao/goldendict/locale/ar_SA.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/ay_WI.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/be_BY.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/be_BY@latin.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/bg_BG.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/cs_CZ.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/de_DE.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/el_GR.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/eo_EO.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/es_AR.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/es_BO.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/es_ES.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/fa_IR.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/fi_FI.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/fr_FR.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/it_IT.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/ja_JP.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/ko_KR.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/lt_LT.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/mk_MK.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/nl_NL.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/pl_PL.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/pt_BR.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/qu_WI.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/ru_RU.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/sk_SK.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/sq_AL.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/sr_SR.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/sv_SE.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/tg_TJ.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/tk_TM.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/tr_TR.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/uk_UA.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/vi_VN.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/zh_CN.qm /usr/local/share/goldendict/locale/
install -m 644 -p /home/jigao/goldendict/locale/zh_TW.qm /usr/local/share/goldendict/locale/
install -m 755 -p /home/jigao/goldendict/redist/icons/goldendict.png /usr/local/share/pixmaps/
strip /usr/local/share/pixmaps/goldendict.png
strip:/usr/local/share/pixmaps/goldendict.png: File format not recognized
Makefile:3785: recipe for target 'install_icons' failed
make: [install_icons] Error 1 (ignored)
install -m 755 -p /home/jigao/goldendict/redist/goldendict.desktop /usr/local/share/applications/
strip /usr/local/share/applications/goldendict.desktop
strip:/usr/local/share/applications/goldendict.desktop: File format not recognized
Makefile:3796: recipe for target 'install_desktops' failed
make: [install_desktops] Error 1 (ignored)
install -m 644 -p /home/jigao/goldendict/help/gdhelp_en.qch /usr/local/share/goldendict/help/
install -m 644 -p /home/jigao/goldendict/help/gdhelp_ru.qch /usr/local/share/goldendict/help/
`
But i still have a goldendict. The problem i cant import the .mdd .mdx dictionary. Which should be possible.

**Comment by vedgy** [comment] 2018-04-26 08:57
I have similar errors during installation and I think they are not critical. I'd like to fix them, but unfortunately don't know how.

I don't use .mdd and .mdx myself, but these formats seem to work for other users. Have you tried importing other dictionary formats?

**Comment by vedgy** [comment] 2018-04-26 18:36
The warnings during installation should be fixed by removing the executable permission from the desktop file and the icon in the *redist* directory. Removing the executable permission might cause issues for users who install Goldendict into their home directory though. See https://unix.stackexchange.com/questions/373239/what-is-the-advantage-of-desktop-files-without-executable-bit-set.

The Gentoo Wiki article linked to in the Stack Exchange question recommends upstreams to remove executable permission and let distributions set it if necessary. Still that same Wiki article links to related bugs, which indicate that making the desktop file non-executable can cause annoyance to some users...

**Comment by vedgy** [comment] 2018-05-21 13:48
#823 is a partial duplicate of this issue.

**Comment by marcelpaulo** [comment] 2018-07-20 11:45
I'm building goldendict from git master (9f06afa) on Xubuntu 18.04, and `make install` targets `install_icons` and `install_desktops` are failing:

```
strip /usr/local/share/pixmaps/goldendict.png                                                                                                                                         
strip:/usr/local/share/pixmaps/goldendict.png: File format not recognized                                                                                                             
Makefile:4413: recipe for target 'install_icons' failed                                                                                                                             
make: [install_icons] Error 1 (ignored)                                                                                                                                             
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/paulo/src/goldendict/redist/goldendict.desktop /usr/local/share/applications/goldendict.desktop                                
strip /usr/local/share/applications/goldendict.desktop                                                                                                                             
strip:/usr/local/share/applications/goldendict.desktop: File format not recognized                                                                                                    
Makefile:4423: recipe for target 'install_desktops' failed                                                                                                                            
make: [install_desktops] Error 1 (ignored)                                                                                                                                     
```

`strip` shouldn't be run on _goldendict.png_ nor on _goldendict.desktop_:

```diff
--- Makefile    2018-07-20 08:05:11.340454024 -0300
+++ /home/paulo/tmp/Makefile    2018-07-20 08:30:34.251170881 -0300
@@ -4412,7 +4412,6 @@
 install_icons: first FORCE
        @test -d $(INSTALL_ROOT)/usr/local/share/pixmaps || mkdir -p $(INSTALL_ROOT)/usr/local/share/pixmaps
        -$(QINSTALL_PROGRAM) /home/paulo/src/goldendict/redist/icons/goldendict.png $(INSTALL_ROOT)/usr/local/share/pixmaps/goldendict.png
-       -strip $(INSTALL_ROOT)/usr/local/share/pixmaps/goldendict.png

 uninstall_icons: FORCE
        -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/pixmaps/goldendict.png
@@ -4422,7 +4421,6 @@
 install_desktops: first FORCE
        @test -d $(INSTALL_ROOT)/usr/local/share/applications || mkdir -p $(INSTALL_ROOT)/usr/local/share/applications
        -$(QINSTALL_PROGRAM) /home/paulo/src/goldendict/redist/goldendict.desktop $(INSTALL_ROOT)/usr/local/share/applications/goldendict.desktop
-       -strip $(INSTALL_ROOT)/usr/local/share/applications/goldendict.desktop

 uninstall_desktops: FORCE
        -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/applications/goldendict.desktop
```

If I understood the build correctly, `qmake` generates _Makefile_ based on _goldendict.po_. But I couldn't find anything in _goldendict.po_ related to `strip`.

**Comment by vedgy** [comment] 2018-08-22 18:27
The executable bit should be removed from the png file - I'm going to create a pull request that does this soon.

I'd just ignore the non-critical error for the desktop file since there seems to be no good solution or workaround. [This](http://lists.mythtv.org/pipermail/mythtv-dev/2005-July/038285.html) workaround seems quite ugly and can cause maintenance issues down the road. I think goldendict should wait for free desktop developers to come to agreement on the desktop file permissions issue and provide a clear guideline for upstream application developers.

**Closed** 2018-08-31 16:02 UTC
