### ISSUE TITLE
When I try to reorder dictionaries in the group they are disappeared

### ISSUE THREAD

**Issue by StasTelnov** [goldendict/goldendict#1288] opened 2020-10-04 18:22 UTC
When I try to reorder dictionaries in the group they are disappeared.

GoldenDict version: 1.5.0-RC2+git
System: Arch Linux 5.8.13-arch1-1

![Peek 2020-10-04 20-39](https://user-images.githubusercontent.com/3819003/95023807-96bbee80-066e-11eb-9ee0-2a1908a13b1f.gif)

**Comment by youngacinonyx** [comment] 2020-10-18 00:24
I'm using the same setup and the problem also happens when trying to reorder the dictionaries in the "Dictionaries" tab. I thought it could be related to the desktop environment, but it happens in both KDE Plasma and LXDE.

**Comment by vedgy** [comment] 2020-10-23 16:48
I can reproduce the bug on Manjaro GNU/Linux in almost latest goldendict master version. Is this a regression caused by a recent Qt update to 5.15.0 or 5.15.1?

**Comment by nonwill** [comment] 2020-10-23 20:59
5.15.1 and 5.12.x also have memory leaks with ui elements. So... stick to 5.9.9...

**Comment by vedgy** [comment] 2020-10-24 08:50
> 5.15.1 and 5.12.x also have memory leaks with ui elements. So... stick with 5.9.9...

And rebuild every program that depends on Qt against version 5.9 each time a new version of that program is released? Seriously? We are using rolling binary distributions where package updates occur very frequently. And *a lot* of popular GNU/Linux software depends on Qt nowadays.

**Comment by nonwill** [comment] 2020-10-24 12:29
Linux has community support and always goes well. Just tested on windows，msvc2019(1927)-x64 build of Qt(5.12.9 and 5.15.1) [leaks a bit serious. Here's the case.](https://bugreports.qt.io/browse/QTBUG-87774).  It should not a compiler bug，because Qt-5.9.9-msvc2019(1927)-x64 and Qt-4.8.7-msvc2019(1927)-x86 all go well and have no memory leaks with the test case. The recent release of Qt changed too much and ...

**Comment by nonwill** [comment] 2020-10-26 12:07
> _ lot_ of popular GNU/Linux software depends on Qt nowadays

It looks like the [patch is on the way and the bug should be fixed.](https://codereview.qt-project.org/c/qt/qtbase/+/318842)..

**Comment by vedgy** [comment] 2020-10-26 12:51
This Goldendict issue is about the wrong drag&drop behavior, which might have been caused by a recent Qt update. It has nothing to do with the memory leak. Let us stop discussing the irrelevant Qt bug here.

**Comment by nonwill** [comment] 2020-10-26 14:06
Yes. 
But the efficient way is to dig it deep and submit/commit an issue with test case to bugreports.qt.io，so that they or the community would care on it. And if it's so serious a bug，it could attract attention sooner and would be fixed later.

**Comment by vedgy** [comment] 2020-11-07 10:45
The bug is absent when goldendict is compiled against Qt 5.5.1 or Qt 4.8.6. Compiling against newer Qt versions is less straightforward, because they don't include Qt WebKit. I suspect the regression was introduced in Qt 5.15.0 or Qt 5.15.1 seeing as it is reported only now and only by Arch/Manjaro users. The closest upstream bug report I could find is [QTBUG-86786](https://bugreports.qt.io/browse/QTBUG-86786), but it affects only Mac and the fix is Mac-specific...

My cursory look at [`DictListWidget`](https://github.com/goldendict/goldendict/blob/0b7c65023cfd94bd8d3213798c03679346b42481/groups_widgets.hh#L69)'s drag&drop related code didn't reveal any obvious issues. The following tentative patch of [`DictListModel::flags`](https://github.com/goldendict/goldendict/blob/0b7c65023cfd94bd8d3213798c03679346b42481/groups_widgets.cc#L196) based on Qt documentation doesn't fix the bug, but allows replacing existing dictionaries by dropping on top of them, that is introduces another usability bug - for all Qt versions:
```diff
   if (index.isValid())
-     return Qt::ItemIsDragEnabled | defaultFlags;
+     return Qt::ItemIsDragEnabled | Qt::ItemIsDropEnabled | defaultFlags;
   else
```

I have noticed that drag&drop between different lists (i.e. between active and inactive (disabled) dictionary lists or between all dictionaries list and a group list) works well in Qt 5.15.1. Only reordering within one list is affected by the bug.

Reverting the most recent commit to relevant GoldenDict code from 2.5 years ago - 6a77c2398613fac1e0d6c7147cb9f4cdc6509d64 - doesn't fix the bug.

I guess the next step is to try and implement a minimum reproducible example and log a Qt bug report. Any other ideas?

**Comment by nonwill** [comment] 2020-11-07 12:46
Two months ago，I found an issue that would crash the app when more than one dictionaries are seleted and then deleted from the group edit widget. I made some fix around DictListWidget and only tested it on windows and ubuntu. But I'm sorry about that the branch which I works on is seriously incompatible with the official repo, the code is for reference only.
[groups_widgets.zip](https://github.com/goldendict/goldendict/files/5504735/groups_widgets.zip)

**Comment by vedgy** [comment] 2020-11-07 14:42
Is *this* bug absent from your branch?

**Comment by nonwill** [comment] 2020-11-07 17:03
I think there may be something wrong with DictListModel and DictListWidget, and my fix really fix the crash issue and this bug  is absent from Ubuntu 20.04 x64. Sorry that I have no experience in making appImage with the latest version of Ubuntu and I'm currently busy porting [my revision](https://nonwill.github.io/post/goldendict/) to macOS and have no time to test it with other version of Linux, but all the files can be downloaded form https://1drv.ms/u/s!AllBS8YFxXjJbFGwCu3UQ6k4Ft4?e=4d8nbd .
![20201108004607](https://user-images.githubusercontent.com/46510529/98446900-f456c580-215b-11eb-8fb9-0a36f9124390.png)

**Comment by vedgy** [comment] 2020-11-08 16:07
Found the Qt bug right away via DuckDuckGo: [QTBUG-87057](https://bugreports.qt.io/browse/QTBUG-87057). Couldn't find it via the apparently inferior JIRA search. As I suspected, it's a regression in Qt 5.15.1. The two linked patches that fix the bug will be included in Qt 5.15.2.

**Comment by vedgy** [comment] 2020-11-28 11:44
After the upgrade to Qt 5.15.2 I can no longer reproduce this bug. @StasTelnov, does the Qt version update fix the bug for you too? If yes, please close this issue.

**Comment by StasTelnov** [comment] 2020-11-28 14:54
@vedgy Yep. It's fixed. Thanks!

**Comment by vedgy** [comment] 2020-11-29 06:41
@StasTelnov, please close this issue then. I cannot close it myself because I am not a GoldenDict maintainer.

**Closed** 2020-11-29 08:57 UTC
