### ISSUE TITLE
shortcut in GNOME

### ISSUE THREAD

**Issue by Devamitta** [goldendict/goldendict#1652] opened 2023-06-09 03:09 UTC
**Describe the bug**

In Fedora GNOME GoldenDict shortcut does not work with apps:
LibreOffice Calc and Writer
Text editor
DB Browser for SQLite
Document Viewer (for PDF)

**Expected behaviour**

selecting word; click Ctrl + Win - it should open selected word in GD, for example with Google Chrome it is working.

**Screenshots**

My settings are:
![image](https://github.com/xiaoyifang/goldendict-ng/assets/39419221/72275f08-3d6b-4eaa-a398-af2b92bbc6c7)

**OS and software versions**

- OS: Fedora Linux 38 (Workstation Edition)
- 64-bit
- GNOME
- Linux 6.3.5-200.fc38.x86_64

**Comment by vedgy** [comment] 2023-06-09 10:04
Duplicate of #913?

**Comment by Devamitta** [comment] 2023-11-19 12:39
> Duplicate of #913?

Indeed

**Closed** 2023-11-19 12:39 UTC
