### ISSUE TITLE
Open goldendict from CLI opens file panel

### ISSUE THREAD

**Issue by gzqx** [goldendict/goldendict#1566] opened 2022-10-28 16:36 UTC
As following screentshot, using `goldendict <a-word>` to open goldendict will somehow open the File panel when start
![Screenshot_20221028_172614](https://user-images.githubusercontent.com/24262751/198687725-3f2a1a64-48c1-4956-b80b-2d24ef4203db.png)

Version: 1.5.0-RC2 (dda311c)
I am using wayland on Fedora Plasma 36.

**Comment by vedgy** [comment] 2022-10-28 17:19
Please close this issue as duplicate of #781. This is the same issue, caused by the same old workaround, even though it is triggered differently.

**Closed** 2022-10-28 17:25 UTC
