### ISSUE TITLE
Goldendict not working under Wayland

### ISSUE THREAD

**Issue by pd1986** [goldendict/goldendict#1200] opened 2019-10-05 00:50 UTC
Goldendict not working under Wayland with QT 5.12,3, Plasma 5.16.5, KDE framework 5.60
Sorry, I have removed Goldendict. I don't have the error message now.

**Comment by vedgy** [comment] 2019-10-07 08:58
This issue must be a duplicate of #935. Please close it.
Try a workaround suggested in a comment to #935.

**Closed** 2020-03-27 14:49 UTC
