### ISSUE TITLE
"File" menu automatically pop-ups when I press Ctrl+F11+F11 on KDE.

### ISSUE THREAD

**Issue by oakszyjrnrdy** [goldendict/goldendict#1193] opened 2019-09-04 16:42 UTC
When i press the hoy key `Ctrl+F11+F11`, the goldendict will pop-up from the background. However, it's weird that the "File" menu will also automatically pop-up even though i didn't click on the "File" menu.

I am using KDE on Manjaro.

![goldendict-bug](https://user-images.githubusercontent.com/26323021/64274468-05afab00-cf76-11e9-8ee1-4509fdf08e2c.png)

**Comment by vedgy** [comment] 2019-09-05 10:12
@oakszyjrnrdy, please close this bug as a duplicate of #781.
A workaround from a comment to that issue:
> A **workaround** for this issue is to uncheck the menu bar under the View menu.

**Closed** 2019-09-06 01:29 UTC
