### ISSUE TITLE
New releases - 'Is this project dead?'

### ISSUE THREAD

**Issue by andradadad** [goldendict/goldendict#1320] opened 2020-11-26 09:15 UTC
I'm seeing updates on the github code, but Early Access to Windows has been more than a year and a half. Official releases are from 2016.

Can you release a new beta version with all the commits you've done?
I'm using windows 7 64bits.

**Comment by masterrite** [comment] 2021-07-14 22:15
Last time this was posted the developer called this behavior "harrassing the developers"

**Comment by xiaoyifang** [comment] 2022-01-21 10:28
try this,if you desperate for a new release :-)
https://github.com/xiaoyifang/goldendict/releases
built with #1400

**Comment by powerman** [comment] 2022-01-21 10:47
Cool! I'm afraid goldendict package was removed from Gentoo Linux. I'll try to add it back when you'll make linux release.

**Comment by xiaoyifang** [comment] 2022-01-22 08:08
https://github.com/xiaoyifang/goldendict/releases/download/prerelease-20220122/GoldenDict-4fa9853-x86_64.AppImage

**Comment by protist** [comment] 2022-02-06 09:30
The stable version of goldendict was [also removed](https://bbs.archlinux.org/viewtopic.php?pid=2020515) from Arch Linux's official repos. It seems like this was due to a lack of newly-tagged releases.

**Comment by vedgy** [comment] 2022-02-06 10:05
I have proposed unofficial/community tagging in #839 but no one supported or rejected that idea yet.

**Comment by nonwill** [comment] 2022-06-18 02:33
[New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).

**Comment by protist** [comment] 2022-06-18 02:52
> [New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).

I don't really know what this is. Spam I guess.

**Comment by nonwill** [comment] 2022-06-18 03:06
> I don't really know what this is. Spam I guess.

Just as you see/say, spams are everywhere and you are just lucky😄.

**Comment by vedgy** [comment] 2023-05-11 12:46
Closing as a duplicate of #953.

**Closed by vedgy** 2023-05-11 12:46 UTC
