### ISSUE TITLE
New release for macOS?

### ISSUE THREAD

**Issue by bcdavasconcelos** [goldendict/goldendict#1276] opened 2020-07-30 03:34 UTC
For the life of me, I can't build the current code into a newer version for myself.
Could a good soul perhaps make a new build/release? Ideally for most platforms, but if that is not possible, for macOS at least. 
Thanks!

**Comment by loyukfai** [comment] 2020-08-26 15:58
A new Android build was just released, so perhaps we'll see new releases for Mac and Windows soon as well.

Cheers.

**Comment by bcdavasconcelos** [comment] 2020-08-26 16:39
That would be lovely.

**Comment by nikita-moor** [comment] 2020-09-25 14:47
Could you also release installer for Window based on Qt5? The last available is on Qt4 and doesn't support WebP. Qt5 binaries work fine, but are not convenient for ordinal users.

**Comment by nonwill** [comment] 2020-11-08 10:35
New macos build with ocr support is available：https://1drv.ms/u/s!AllBS8YFxXjJbFGwCu3UQ6k4Ft4?e=4d8nbd or [b8sh](https://pan.baidu.com/s/1IlOlf-lhJsDm-XIdDigECQ)

**Comment by bcdavasconcelos** [comment] 2020-11-08 14:15
Thank you, @nonwill!

**Comment by nonwill** [comment] 2020-11-10 06:47
@bcdavasconcelos @nikita-moor
A fix build for macOS has been released. Fixed issue with plugins(failed to load Audio and OCR engines). 
All builds are updated.

**Comment by bcdavasconcelos** [comment] 2020-11-10 12:38
Thanks again! 

Were you able to use dark mode on macOS or is this not supported yet?

**Comment by nonwill** [comment] 2020-11-10 13:28
> Were you able to use dark mode on macOS or is this not supported yet?

Sorry about that the macOS version is built & tested by friends and I‘ve no macOS at hand now.

**Comment by xiaoyifang** [comment] 2022-02-12 13:24
related to  https://github.com/goldendict/goldendict/issues/1427#issuecomment-1037224611

**Comment by loyukfai** [comment] 2022-05-25 15:44
Tried these?

https://github.com/xiaoyifang/goldendict/releases

**Comment by nonwill** [comment] 2022-05-25 15:51
[Tried these?](https://nonwill.github.io/post/goldendict/)

**Comment by danfe** [comment] 2022-06-07 05:56
While there is Early Access Builds page, it is mostly of an interest to end-users.  For packagers, it would be nice to have certain Git commits _tagged_ from time to time, because right now the latest tag is 1.5.0-RC2 which is from 2016.

**Comment by danfe** [comment] 2022-06-07 09:51
> So it would never have been left hanging if a mere tag would have solved the problem.

Sorry, I don't quite understand what point you're trying to make.  I'm saying that, seeing the steady stream of commits (bugfixes and improvements), having most recently tagged release candidate being six-year old looks, well, rather strange.

**Comment by nonwill** [comment] 2022-06-07 10:18
> most recently tagged release candidate being six years old looks

But builds have been never really stopped. It's never been a problem on Linux, and @Abs62 has never stopped updating his builds for Windows, also there are many different(other) builds for macOS(Linux/Windows) too. It's just that none of these builds have been uploaded to the official website or here, which perhaps is the problem?

**Comment by nonwill** [comment] 2022-06-07 13:31
Yes, this is the big problem, not just on FreeBSD, but also on many Linux platforms.
As far as I know, recently, developers who are still very active and can guarantee the quality of submissions may only be @Abs62 and @vedgy ...  
Given the current status of the GoldenDict project, it may be better to regularly pull the latest code......

**Comment by danfe** [comment] 2022-06-08 06:37
> Given the current status of the GoldenDict project, it may be better to regularly pull the latest code.

That's what I'm currently doing, but then again: what is the best time to update?  Once a month, two, six?  How the package maintainer (not a GoldenDict developer who's in the kitchen) would make this guess and make it right?

> I have proposed unofficial/community tagging as a workaround in #839 but no one supported or rejected that idea yet.

Hmm, I somehow missed that issue when searching for appropriate place to bring up the tagging question. 
 I've commented there as well.  In short, no, unofficial/community "tagging" in the Wiki would not help, we need the casual, standard tags in Git.  (Note that _tags_ do not imply _releases_, there are many projects on GitHub with zero releases but tagging their sources more or less regularly.)

**Comment by nonwill** [comment] 2022-06-18 02:25
[New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).

**Comment by nonwill** [comment] 2022-07-11 05:38
![](https://s3.bmp.ovh/imgs/2022/07/11/e8bedb4fda7214ce.gif)
A [new release supporting Mac OS X 's built-in Dictionaries](https://nonwill.github.io/gdocr/GoldenDict-OCR-Changelog/) is coming soon...

**Comment by nonwill** [comment] 2022-07-28 07:34
![](https://s3.bmp.ovh/imgs/2022/07/11/e8bedb4fda7214ce.gif)
[New release supporting Mac OS X 's built-in Dictionaries](https://nonwill.github.io/gdocr/GoldenDict-OCR-Changelog/) is coming ...

**Comment by nonwill** [comment] 2022-08-06 16:10
[Mac OS X 's built-in Dictionaries](https://nonwill.github.io/gdocr/GoldenDict-OCR-Changelog/) are [fully supported on Windows/macOS/Linux](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) now.
![](https://s3.bmp.ovh/imgs/2022/08/06/d9651876ae94a104.gif)
![](https://s3.bmp.ovh/imgs/2022/07/11/e8bedb4fda7214ce.gif)
#839 #953 #1340 #1348

**Comment by nonwill** [comment] 2022-08-08 04:18
```
TTY Abbreviations(TTY Abbreviations Dictionary.dictionary)
阿拉伯文-英文(Arabic - English.dictionary)
波兰文-英文(Polish - English.dictionary)
丹麦文(Danish.dictionary)
德文(Duden Dictionary Data Set I.dictionary)
德文-英文(German - English.dictionary)
俄文(Russian.dictionary)
俄文-英文(Russian - English.dictionary)
法文(French.dictionary)
法文-德文(French - German.dictionary)
法文-英文(French - English.dictionary)
繁体中文(Traditional Chinese.dictionary)
繁体中文（香港）(Traditional Chinese Common Words.dictionary)
繁体中文-英文(Traditional Chinese - English.dictionary)
繁体中文-英文习语(Traditional Chinese - English Idioms.dictionary)
古吉拉特文-英文(Gujarati - English.dictionary)
韩文(Korean.dictionary)
韩文-英文(Korean - English.dictionary)
荷兰文(Dutch.dictionary)
荷兰文-英文(Dutch - English.dictionary)
简体中文(The Standard Dictionary of Contemporary Chinese.dictionary)
简体中文成语(Simplified Chinese Idioms.dictionary)
简体中文-日文(Simplified Chinese - Japanese.dictionary)
简体中文同义词词典(Simplified Chinese Thesaurus.dictionary)
简体中文-英文(Simplified Chinese - English.dictionary)
美式英文(New Oxford American Dictionary.dictionary)
美式英文同义词词典(Oxford American Writer_s Thesaurus.dictionary)
挪威文(Norwegian.dictionary)
葡萄牙文(Portuguese.dictionary)
葡萄牙文-英文(Portuguese - English.dictionary)
日文(Sanseido Super Daijirin.dictionary)
日文-英文(Sanseido The WISDOM English-Japanese Japanese-English Dictionary.dictionary)
瑞典文(Swedish.dictionary)
泰卢固文-英文(Telugu - English.dictionary)
泰米尔文-英文(Tamil - English.dictionary)
泰文(Thai.dictionary)
泰文-英文(Thai - English.dictionary)
土耳其文(Turkish.dictionary)
维基百科(Wikipedia.wikipediadictionary)
乌尔都文-英文(Urdu - English.dictionary)
西班牙文(Spanish.dictionary)
西班牙文-英文(Spanish - English.dictionary)
希伯来文(Hebrew.dictionary)
意大利文(Italian.dictionary)
意大利文-英文(Italian - English.dictionary)
印地文(Hindi.dictionary)
印地文-英文(Hindi - English.dictionary)
印度尼西亚文-英文(Indonesian - English.dictionary)
英式英文(Oxford Dictionary of English.dictionary)
英式英文同义词词典(Oxford Thesaurus of English.dictionary)
越南文-英文(Vietnamese - English.dictionary)
粤语-英文(Cantonese - English.dictionary)
```
[Using Apple OSX’s built-in Dictionary on Linux and Windows](https://nonwill.github.io/gdocr/GoldenDict-OCR-Free-Dictionaries/#1-apple-osxs-built-in-dictionaryhttpssupportapplecomzh-cnguidedictionarywelcomemac%E9%AB%98%E5%A4%A7%E4%B8%8A%E5%8F%88%E9%AB%98%E8%B4%A8%E9%87%8F%E7%9A%84apple%E8%BE%9E%E4%B9%A6httpssupportapplecomzh-cnguidedictionarywelcomemac).

**Comment by nonwill** [comment] 2022-10-12 03:30
**Perfect** [support for Apple OSX' Dictionaries](https://nonwill.github.io/gdocr/GoldenDict-OCR-Free-Dictionaries/#1-apple-osxs-built-in-dictionaryhttpssupportapplecomzh-cnguidedictionarywelcomemac%E9%AB%98%E5%A4%A7%E4%B8%8A%E5%8F%88%E9%AB%98%E8%B4%A8%E9%87%8F%E7%9A%84apple%E8%BE%9E%E4%B9%A6httpssupportapplecomzh-cnguidedictionarywelcomemac) now：
![macos_dict_lookup_words](https://user-images.githubusercontent.com/46510529/195242720-015116ed-d82d-4e33-9925-fa72801589f2.gif)

**Comment by nonwill** [comment] 2022-10-16 23:37
**Perfect** [support for Apple OSX' Dictionaries](https://nonwill.github.io/gdocr/GoldenDict-OCR-Free-Dictionaries/#1-apple-osxs-built-in-dictionaryhttpssupportapplecomzh-cnguidedictionarywelcomemac%E9%AB%98%E5%A4%A7%E4%B8%8A%E5%8F%88%E9%AB%98%E8%B4%A8%E9%87%8F%E7%9A%84apple%E8%BE%9E%E4%B9%A6httpssupportapplecomzh-cnguidedictionarywelcomemac) now：
![macos_dict_lookup_words](https://user-images.githubusercontent.com/46510529/195242720-015116ed-d82d-4e33-9925-fa72801589f2.gif)

**Comment by vedgy** [comment] 2023-05-11 12:47
Closing as a duplicate of #953.

**Closed by vedgy** 2023-05-11 12:47 UTC
