### ISSUE TITLE
Query error while accessing German wiktionary

### ISSUE THREAD

**Issue by ayunah** [goldendict/goldendict#693] opened 2016-04-19 18:00 UTC
Query error while accessing German wiktionary: Query error: XML parse error: unexpected end of file at 1,1 GoldenDict 1.5.0, Ubuntu 14.4 
![selection_020](https://cloud.githubusercontent.com/assets/4592909/14649922/48b6db4e-067a-11e6-924a-ab479baa3621.png)

**Comment by Abs62** [comment] 2016-04-19 18:35
Duplicate of issue #654

**Closed by Abs62** 2016-04-19 18:35 UTC
