### ISSUE TITLE
goldendict not work when use hotkeys in okular

### ISSUE THREAD

**Issue by shoshtari** [goldendict/goldendict#1378] opened 2021-05-04 23:30 UTC
Hi!
when i am working with Firefox and use hotkeys it works without any problem, but in Okular it doesn't works

**Comment by vedgy** [comment] 2021-05-08 06:41
Both hotkeys work for me in Okular 21.04, Manjaro, Xfce.

You can pin the scan popup window using the pin button in the top right corner of the scan popup; then position the pinned scan popup window alongside a non-maximized Okular window. If you do not want to pin the scan popup window, experiment with **ScanPopup unpinned window flags** combobox and checkbox on the *Advanced* tab of GoldenDict's preferences.

**Comment by vedgy** [comment] 2021-05-08 08:33
If your issue is not with the scan popup visibility, then maybe it's a duplicate of #650, #858, #913 or #1290. Several workarounds are proposed in comments to these issues. If this issue is indeed a duplicate, please close it and comment under one of the older issues.

**Closed** 2021-05-08 12:32 UTC
