### ISSUE TITLE
Can't remember Favorite

### ISSUE THREAD

**Issue by gttwork** [goldendict/goldendict#979] opened 2018-03-24 12:54 UTC
The "Favorite" function is great. But when I restart my computer, it can't remember the newly added words. If I use Task Manager kill the GoldenDict process, it's the same. If I exit the GoldenDict before restart computer, then everything is OK. The "History" function works very well, If I use Task Manager kill the GoldenDict process, it still remember the words. 
OS: Windows 10.
Thank you for your hard work.

**Comment by gttwork** [comment] 2018-03-24 13:31
It can't remember the words when I turn off my computer. I have to exit GD before I turn off my computer.

**Comment by vedgy** [comment] 2018-03-24 15:11
Calling `FavoritesModel::saveData()` in `MainWindow::commitData()` should fix the issue.

**Comment by Abs62** [comment] 2018-03-26 15:24
**gttwork**, try [this build](http://www.mediafire.com/file/nzy95zbmwqcdub8/goldendict-1.5.0-RC2-262-g5552c18%28EXE+only%29.7z).

**Comment by vedgy** [comment] 2018-03-26 16:33
I just noticed that `QHotkeyApplication` "overrides" [QApplication::commitData()](https://doc.qt.io/archives/qt-4.8/qapplication.html#commitData), which is no longer available in Qt5. When I add the C++11 keyword `override` to `QHotkeyApplication::commitData()`'s declaration, it doesn't compile with Qt5. The portable Qt4 and Qt5 approach is to connect to the [QApplication::commitDataRequest signal](https://doc.qt.io/qt-5/qguiapplication.html#commitDataRequest).

So if the attached build uses Qt5, it probably won't fix this issue.

I noticed a related issue with `MainWindow::commitDataCompleted`. From [QApplication::commitDataRequest signal](https://doc.qt.io/qt-5/qguiapplication.html#commitDataRequest) documentation:
> You should not exit the application within this signal. Instead, the session manager may or may not do this afterwards, depending on the context.

If the session manager decides to keep the application running (e.g. if the user cancels logout), then goldendict won't save any changes after this failed logout attempt. There also might be issues caused by calling `scanPopup.reset();` in `MainWindow::commitData()` under this scenario. Though this is a quite rare case and might be ignored for the time being.

**Comment by gttwork** [comment] 2018-03-26 21:43
It works (portable Qt4). Thank you very much.

**Comment by Abs62** [comment] 2018-03-27 15:13
[goldendict-1.5.0-RC2-263-g2ff7e4e(EXE only).7z](http://www.mediafire.com/file/zzet9ihumy26pw0/goldendict-1.5.0-RC2-263-g2ff7e4e%28EXE+only%29.7z) - Qt5-based version also should work.

**Comment by vedgy** [comment] 2018-03-27 15:33
The implementation seems to cover all cases, though not very efficiently.
The most inefficient part seems to be this:
```cpp
    // Reinit popup window if necessary (when called from session manager)
    if( init_popup )
      makeScanPopup();
```
The few relevant lines of code in `~ScanPopup()` could be extracted in a separate function, then this function could be called from `commitData()` instead of destroying, then creating another `ScanPopup` instance. This faster approach also seems less risky. What if there is some pointer dependency of the `ScanPopup` instance and some other object?

**Comment by Abs62** [comment] 2018-03-27 18:46
It's reasonable.

**Comment by vedgy** [comment] 2018-03-27 19:07
The code looks good now. Thanks.

**Closed** 2018-04-11 04:32 UTC
