### ISSUE TITLE
Support for ld2 dictionary

### ISSUE THREAD

**Issue by masterrite** [goldendict/goldendict#752] opened 2016-09-12 21:03 UTC
Hi,

Can we make windows and mac versions of goldendict support .ld2 dictionaries as well? I'm thinking about moving from lingoes to goldendict and don't want to redownload my dictionaries,

Thanks!

**Comment by Abs62** [comment] 2017-07-11 09:49
Duplicate of issue #282

**Closed by Abs62** 2017-07-11 09:49 UTC
